# -------------------------------------------------------------------------------------
# Privacy Configuration
# See: https://gohugo.io/about/hugo-and-gdpr/
# -------------------------------------------------------------------------------------

[X]
  enableDNT = true
[youtube]
  privacyEnhanced = true
